// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package oapi

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// エラー情報
type Error struct {
	// エラー内容
	Detail string `json:"detail"`

	// エラーコード
	ErrorCode string `json:"errorCode"`

	// ステータスコード
	StatusCode float32 `json:"statusCode"`
}

// グループデータ
type Group struct {
	// グループID
	Id string `gorm:"primaryKey;type:varchar(36)" json:"id"`

	// グループ名
	Name string `gorm:"type:varchar(100);not null" json:"name"`
}

// グループ情報
type RequestGroupsPost struct {
	// メンバーID
	MemberId string `json:"member_id"`

	// グループ名
	Name string `json:"name"`
}

// ログイン情報
type RequestLogin struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// 追加するユーザー情報
type RequestUser struct {
	MemberId string `json:"member_id"`
	Name     string `json:"name"`
}

// エラー結果
type ResultError struct {
	// エラー情報
	Error Error `json:"error"`

	// 結果
	Result bool `json:"result"`
}

// グループ一覧情報
type ResultGroupsGet struct {
	// 件数
	Count int `json:"count"`

	// 一覧データ
	Data []Group `json:"data"`
}

// グループ作成成功
type ResultGroupsPost struct {
	// グループデータ
	Data Group `json:"data"`

	// 結果
	Result bool `json:"result"`
}

// 成功
type ResultOK struct {
	// 結果
	Result bool `json:"result"`
}

// ユーザー情報
type ResultUser User

// ユーザー一覧
type ResultUsers struct {
	// 件数
	Count int `json:"count"`

	// ユーザー
	Data []User `json:"data"`
}

// ユーザー情報
type User struct {
	// ユーザーID
	Id string `json:"id"`

	// 名前
	Name string `json:"name"`
}

// UserId defines model for userId.
type UserId string

// PostApiClientGroupsJSONBody defines parameters for PostApiClientGroups.
type PostApiClientGroupsJSONBody RequestGroupsPost

// GetApiClientUsersParams defines parameters for GetApiClientUsers.
type GetApiClientUsersParams struct {
	// メンバーID
	MemberId string `json:"member_id"`
}

// PostApiClientUsersJSONBody defines parameters for PostApiClientUsers.
type PostApiClientUsersJSONBody RequestUser

// PostApiLoginJSONBody defines parameters for PostApiLogin.
type PostApiLoginJSONBody RequestLogin

// PostApiClientGroupsJSONRequestBody defines body for PostApiClientGroups for application/json ContentType.
type PostApiClientGroupsJSONRequestBody PostApiClientGroupsJSONBody

// PostApiClientUsersJSONRequestBody defines body for PostApiClientUsers for application/json ContentType.
type PostApiClientUsersJSONRequestBody PostApiClientUsersJSONBody

// PostApiLoginJSONRequestBody defines body for PostApiLogin for application/json ContentType.
type PostApiLoginJSONRequestBody PostApiLoginJSONBody

