openapi: 3.0.0
tags: []
info:
  title: sample-api
  version: '1.0'
  description: SAMPLE用のAPIリファレンス
  contact:
    name: tribeat
    url: 'https://tribeat.com'
    email: info@tribeat.com

paths:
  /api/healthcheck:
    get:
      summary: ヘルスチェック
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resultOK'
        '500':
          description: NG
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resultError'
  /api/login:
    post:
      summary: ログイン
      tags: []
      requestBody:
        description: ログイン情報
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestLogin'
      response:
        '201':
          description: ログイン成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resultOK'
        '401':
          description: ログイン失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resultError'

components:
  schemas:
    resultOK:
      type: object
      description: 成功
      properties:
        result:
          type: boolean
          description: 結果
      required:
        - result
          
    resultError:
      type: object
      description: エラー結果
      properties:
        result:
          type: boolean
          description: 結果
        error:
          $ref: '#/components/schemas/error'
      required:
        - result
        - error
    error:
      type: object
      description: エラー情報
      properties:
        statusCode:
          type: number
          description: ステータスコード
        errorCode:
          type: string
          description: エラーコード
        detail:
          type: string
          description: エラー内容
      required:
        - statusCode
        - errorCode
        - detail

    requestLogin:
      type: object
      description: ログイン情報
      properties:
        email:
          type: string
          maxLength: 260
          format: email
        password:
          type: string
          maxLength: 100
          minLength: 6
          pattern: ^[A-Za-z0-9]+$
      required:
        - email
        - password


