// Package oapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package oapi

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Error defines model for error.
type Error struct {

	// エラー内容
	Detail string `json:"detail"`

	// エラーコード
	ErrorCode string `json:"errorCode"`

	// ステータスコード
	StatusCode float32 `json:"statusCode"`
}

// RequestLogin defines model for requestLogin.
type RequestLogin struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ResultError defines model for resultError.
type ResultError struct {

	// エラー情報
	Error Error `json:"error"`

	// 結果
	Result bool `json:"result"`
}

// ResultOK defines model for resultOK.
type ResultOK struct {

	// 結果
	Result bool `json:"result"`
}

// PostApiLoginJSONBody defines parameters for PostApiLogin.
type PostApiLoginJSONBody RequestLogin

// PostApiLoginRequestBody defines body for PostApiLogin for application/json ContentType.
type PostApiLoginJSONRequestBody PostApiLoginJSONBody

